### ISSUE TITLE
Bug in ontology.asp

### ISSUE THREAD

**Issue by dschaehi** [phohenecker/family-tree-data-gen#1]
Hi,

I found a bug in the following rules. For example
`daughterOf(X, Y)                   :- childOf(Y, X), female(X).`
should be
`daughterOf(X, Y)                   :- childOf(X, Y), female(X).`

https://github.com/phohenecker/family-tree-data-gen/blob/fcbfeb07c55918a2584ebb2e1e7a4b35c1dc3fb4/src/main/asp/ontology.asp#L109-L114

**Comment by phohenecker** [comment]
Hi @dschaehi. Many thanks! I fixed the rules.
